# Generated by Django 5.2.11 on 2026-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Jewellery', max_length=100),
        ),
    ]
